---
ID: "23868f5f-0d63-4b8d-910f-194acb74e48d"
Parent: "4a2dc876-d4ba-4876-a1be-f8ac35fc80d5"
Template: "4a2dc876-d4ba-4876-a1be-f8ac35fc80d5"
Path: /sitecore/templates/Project/Hackathon/Content Types/Email Template/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T123341Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
