---
ID: "29ecb32e-a0fa-4ac9-8c24-6817fd1eb4f0"
Parent: "4888c3ea-1a48-448e-9bc2-dc7c45525897"
Template: "4888c3ea-1a48-448e-9bc2-dc7c45525897"
Path: /sitecore/templates/Project/Hackathon/Page Types/Home/__Standard Values
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{EB3C41D1-DC06-4819-BDE0-F52A1C1652FC}" />
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T064718Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
