---
ID: "3d731a38-d951-4d6a-a2b7-038391a20bf4"
Parent: "00fd7ab9-3b0c-473c-8960-73fb1a8e3028"
Template: "00fd7ab9-3b0c-473c-8960-73fb1a8e3028"
Path: /sitecore/templates/Project/Hackathon/Folders/Global Data/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T124030Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
