---
ID: "eb3c41d1-dc06-4819-bde0-f52a1c1652fc"
Parent: "1473202b-4957-431d-864f-cbc5e943444a"
Template: "3a45a723-64ee-4919-9d41-02fd40fd1466"
Path: /sitecore/layout/Layouts/Project/Hackathon/Default
DB: master
SharedFields:
- ID: "a036b2bc-ba04-44f6-a75f-bae6cd242abf"
  Hint: Path
  Value: /Views/Hackathon/Layouts/Default.cshtml
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T061731Z
