---
ID: "93c060bd-4561-4831-92b7-83f8c1be4d4e"
Parent: "2c8833b9-b078-41fc-9bbb-3c43419fa033"
Template: "2c8833b9-b078-41fc-9bbb-3c43419fa033"
Path: /sitecore/templates/Project/Hackathon/Content Types/Site Root/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{4888C3EA-1A48-448E-9BC2-DC7C45525897}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T064423Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
