---
ID: "0782eea6-977d-4a13-9853-1a816c448534"
Parent: "3875ff27-04b9-4476-abd4-bb4d777663f6"
Template: "3875ff27-04b9-4476-abd4-bb4d777663f6"
Path: /sitecore/templates/Feature/Teams/_Teams Listing/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T234607Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
